### ISSUE TITLE
flush, clear 다시 알아보기, toPartDto, toPartDtoList 도입 검토

### ISSUE THREAD

**Issue by CHANEE-personal** [CHANEE-personal/tsp_project#64]
1. @Modifying(clearAutomatically = true)에 대해 다시 알아보기 -> 주로 대량의 데이터 insert, update, delete할 때 사용 -> 벌크연산
2. entityManager flush, clear 다시 알아보기
3. toPartDto, toPartDtoList 도입 검토

**Comment by kangtae** [comment]
오호
